"""role update

Revision ID: 4efa2ec0197f
Revises: fcf0d27c3127
Create Date: 2024-10-27 12:49:15.790730

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4efa2ec0197f'
down_revision: Union[str, None] = 'fcf0d27c3127'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('can_apply_for_specialist', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('can_view_profile', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('can_fill_evaluation_form', sa.Boolean(), nullable=False))
    op.add_column('role', sa.Column('can_edit_user_data', sa.Boolean(), nullable=False))
    op.drop_column('role', 'permissions')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('permissions', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.drop_column('role', 'can_edit_user_data')
    op.drop_column('role', 'can_fill_evaluation_form')
    op.drop_column('role', 'can_view_profile')
    op.drop_column('role', 'can_apply_for_specialist')
    # ### end Alembic commands ###
