"""user estate solve problem

Revision ID: 50b8639ac5b8
Revises: cf21af5f5baa
Create Date: 2024-10-29 01:16:34.937712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50b8639ac5b8'
down_revision: Union[str, None] = 'cf21af5f5baa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('estate',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('area_total', sa.Float(), nullable=False),
                    sa.Column('floor_number', sa.Integer(), nullable=False),
                    sa.Column('total_floors', sa.Integer(), nullable=True),
                    sa.Column('building_type', sa.String(), nullable=False),
                    sa.Column('year_built', sa.Integer(), nullable=True),
                    sa.Column('ceiling_height', sa.Float(), nullable=True),
                    sa.Column('has_balcony', sa.Boolean(), nullable=True),
                    sa.Column('condition', sa.String(), nullable=True),
                    sa.Column('address', sa.String(), nullable=False),
                    sa.Column('heating', sa.String(), nullable=True),
                    sa.Column('water_supply', sa.Boolean(), nullable=True),
                    sa.Column('sewerage', sa.Boolean(), nullable=True),
                    sa.Column('electricity', sa.Boolean(), nullable=True),
                    sa.Column('gas', sa.Boolean(), nullable=True),
                    sa.Column('internet', sa.Boolean(), nullable=True),
                    sa.Column('user_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_estate_id'), 'estate', ['id'], unique=False)
    op.create_table('report',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('estimated_value', sa.Float(), nullable=False),
                    sa.Column('price_per_sqm', sa.Float(), nullable=False),
                    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
                    sa.Column('estate_id', sa.Integer(), nullable=False),
                    sa.ForeignKeyConstraint(['estate_id'], ['estate.id'], ),
                    sa.PrimaryKeyConstraint('id')
                    )
    op.create_index(op.f('ix_report_id'), 'report', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
