"""spec change

Revision ID: fcf0d27c3127
Revises: 22c374f72c52
Create Date: 2024-10-27 01:17:45.445962

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fcf0d27c3127'
down_revision: Union[str, None] = '22c374f72c52'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('specialist', sa.Column('is_approved', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('specialist', 'is_approved')
    # ### end Alembic commands ###
